# Generated by Django 4.1.7 on 2023-03-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleroute",
            name="securityteam_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="deliveries.securityteam",
            ),
            preserve_default=False,
        ),
    ]
